FROM node:16.13.0-buster-slim

RUN apt update && \
    apt install -y --no-install-recommends \
    tini && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN npm i -g npm &\
    npm i -g @vue/cli

WORKDIR /app

COPY package*.json ./
RUN npm ci

ENV NUXT_HOST 0.0.0.0
ENV NUXT_PORT 3000

EXPOSE 3000

ENTRYPOINT ["tini", "--"]
CMD ["sleep", "infinity"]
