FROM node:16.13.0-buster-slim

RUN apt update && \
    apt install -y --no-install-recommends \
    tini && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN npm i -g npm &\
    npm i -g @vue/cli serve

WORKDIR /app

COPY package*.json ./
RUN npm ci

RUN chmod 777 /app/node_modules/@vue/cli-service/lib/commands/build

ENV CWL_INPUTS_PARSER_URL https://cwl-inputs-parser.azurewebsites.net
ENV WES_URL http://localhost:1122
ENV VUE_PORT 3000

EXPOSE 3000

ENTRYPOINT ["tini", "--"]
CMD ["sleep", "infinity"]
